"""Agrega excepciones_horarios

Revision ID: 27665e04bf59
Revises: a78cc7b03eb7
Create Date: 2026-04-05 22:22:21.387235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27665e04bf59'
down_revision: Union[str, Sequence[str], None] = 'a78cc7b03eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excepciones_horarios',
    sa.Column('id_excepcion', sa.Integer(), nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fin', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['id_recurso'], ['recursos.id_recurso'], ),
    sa.PrimaryKeyConstraint('id_excepcion')
    )
    op.create_index(op.f('ix_excepciones_horarios_id_excepcion'), 'excepciones_horarios', ['id_excepcion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excepciones_horarios_id_excepcion'), table_name='excepciones_horarios')
    op.drop_table('excepciones_horarios')
    # ### end Alembic commands ###
