"""Esquema universal SQLite

Revision ID: a78cc7b03eb7
Revises: 
Create Date: 2026-04-05 22:11:03.307716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78cc7b03eb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias_no_disponibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dias_no_disponibles_id'), 'dias_no_disponibles', ['id'], unique=False)
    op.create_table('negocios',
    sa.Column('id_negocio', sa.Integer(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=100), nullable=False),
    sa.Column('tipo_industria', sa.String(length=50), nullable=True),
    sa.Column('configuracion_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id_negocio')
    )
    op.create_index(op.f('ix_negocios_id_negocio'), 'negocios', ['id_negocio'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_telegram', sa.BigInteger(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo_electronico', sa.String(length=100), nullable=True),
    sa.Column('acepta_privacidad', sa.Boolean(), nullable=True),
    sa.Column('fecha_aceptacion_terminos', sa.DateTime(), nullable=True),
    sa.Column('version_terminos_aceptada', sa.String(length=10), nullable=True),
    sa.Column('recibir_marketing', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_id_telegram'), 'usuarios', ['id_telegram'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('entidades_sujetos',
    sa.Column('id_sujeto', sa.Integer(), nullable=False),
    sa.Column('id_usuario_dueno', sa.Integer(), nullable=False),
    sa.Column('nombre_sujeto', sa.String(length=100), nullable=False),
    sa.Column('metadatos_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_dueno'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sujeto')
    )
    op.create_index(op.f('ix_entidades_sujetos_id_sujeto'), 'entidades_sujetos', ['id_sujeto'], unique=False)
    op.create_table('recursos',
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('id_negocio', sa.Integer(), nullable=False),
    sa.Column('nombre_recurso', sa.String(length=100), nullable=False),
    sa.Column('tipo_recurso', sa.String(length=50), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_negocio'], ['negocios.id_negocio'], ),
    sa.PrimaryKeyConstraint('id_recurso')
    )
    op.create_index(op.f('ix_recursos_id_recurso'), 'recursos', ['id_recurso'], unique=False)
    op.create_table('servicios',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_negocio', sa.Integer(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=100), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_negocio'], ['negocios.id_negocio'], ),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_index(op.f('ix_servicios_id_servicio'), 'servicios', ['id_servicio'], unique=False)
    op.create_table('citas',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('id_negocio', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_sujeto', sa.Integer(), nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=False),
    sa.Column('estado_cita', sa.String(length=20), nullable=True),
    sa.Column('precio_cobrado', sa.Float(), nullable=True),
    sa.Column('recordatorio_24h_enviado', sa.Boolean(), nullable=True),
    sa.Column('recordatorio_2h_enviado', sa.Boolean(), nullable=True),
    sa.Column('fecha_recordatorio_solicitado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_negocio'], ['negocios.id_negocio'], ),
    sa.ForeignKeyConstraint(['id_recurso'], ['recursos.id_recurso'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], ),
    sa.ForeignKeyConstraint(['id_sujeto'], ['entidades_sujetos.id_sujeto'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_index(op.f('ix_citas_id_cita'), 'citas', ['id_cita'], unique=False)
    op.create_table('horarios_recursos',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fin', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['id_recurso'], ['recursos.id_recurso'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_index(op.f('ix_horarios_recursos_id_horario'), 'horarios_recursos', ['id_horario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horarios_recursos_id_horario'), table_name='horarios_recursos')
    op.drop_table('horarios_recursos')
    op.drop_index(op.f('ix_citas_id_cita'), table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_servicios_id_servicio'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_recursos_id_recurso'), table_name='recursos')
    op.drop_table('recursos')
    op.drop_index(op.f('ix_entidades_sujetos_id_sujeto'), table_name='entidades_sujetos')
    op.drop_table('entidades_sujetos')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_telegram'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_negocios_id_negocio'), table_name='negocios')
    op.drop_table('negocios')
    op.drop_index(op.f('ix_dias_no_disponibles_id'), table_name='dias_no_disponibles')
    op.drop_table('dias_no_disponibles')
    # ### end Alembic commands ###
